Repository milieuinfo/webcomponent-vl-ui-util, pull requests merged in 2020-05, with the labels that each got.

#142 Update dependency chromedriver to v81
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#135 Update dependency sinon to v9
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#133 Update dependency fetch-mock to v9
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#159 Lock file maintenance
  package-lock.json
Labels: chore, dependencies, renovate

#161 Oplossing voor build problemen min variant
  build.js
  package-lock.json
  package.json
  test/multiple/expected/vl-example-all.min.js
  test/multiple/expected/vl-example.min.js
Labels: bug

#141 .npmignore toevoegen
  .gitignore
  .npmignore
  package.json
Labels: chore

#162 Mocha configuratie kopieerbaar maken door .npmignore exclude
  .npmignore
Labels: bug

#165 Update dependency yaml to v1.10.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#166 Voeg luxon toe als dep
  package-lock.json
  package.json
Labels: chore

#168 Update dependency copyfiles to v2.3.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#167 Update dependency chromedriver to v83
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#169 Rapporteer enkel eslint errors, niet de build laten falen
  package.json
Labels: chore

#170 Eslint errors tonen als warning
  .eslintrc.json
  package-lock.json
  package.json
Labels: chore

#171 Lockfile maintenance
  package-lock.json
Labels: chore

#172 Update dependency sass to v1.26.6
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#173 Update dependency sass to v1.26.7
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
