Repository milieuinfo/webcomponent-vl-ui-util, pull requests merged in 2020-10, with the labels that each got.

#216 Zet checkDependencies test in comment want deze moet nog door @coemans bekeken worden
  .vscode/launch.json
  package-lock.json
  package.json
  scripts/checkDependencies.js
  test/checkDependencies.test.js
Labels: bugfix

#217 Voeg force-recreate toe aan run command
  bamboo-specs/bamboo.yml
Labels: bugfix

#215 Update dependencies
  package-lock.json
  package.json
Labels: chore

#219 Wijziging standaard assignee
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
Labels: chore

#220 Publiceer testresultaten via stdout en junit
  .mocharc-util.js
  bamboo-specs/bamboo.yml
  docker-compose.yml
  package-lock.json
  package.json
  reporter-config.json
Labels: chore

#221 Schakel het downloaden van de sauce-connect binary en het downloaden van de drivers via wct uit
  test/docker-compose.yml
Labels: chore, enhancement

#222 De dist map mag niet genegeerd worden door git
  .gitignore
Labels: bug

#223 Ignore .sass-cache folder
  templates/.gitignore.template
Labels: chore

#224 Update .mocharc.js
  .mocharc.js
  package.json
Labels: chore

#225 Genereer WCT Junit reports
  package-lock.json
  package.json
  wct.docker.conf.json
  wct.local.conf.json
Labels: chore

#226 Verwijder foutieve wct config
  wct.docker.conf.json
  wct.local.conf.json
Labels: chore

#227 reporter rework
  .mocharc.js
  reporter-config.json
Labels: chore

#228 Add WCT Junit reporter
  package-lock.json
  package.json
  wct.docker.conf.json
  wct.local.conf.json
Labels: chore

#229 Verwijder overbodige dependencies
  package-lock.json
  package.json
Labels: chore

#230 Introductie wct-junit-reporter dependency
  package-lock.json
  package.json
  wct.local.conf.json
Labels: chore

#231 Fix typo en pas pad voor util test reports aan
  .mocharc-util.js
  reporter-config-util.json
Labels: bugfix

#195 Controleer voor het releasen of er nog op een branch gedepend wordt
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  .gitignore
  .mocharc-util.js
  .mocharc.js
  bamboo-specs/bamboo.yml
  bamboo/bamboo-spec.js
  bamboo/utils/util.js
  docker-compose.yml
  package-lock.json
  package.json
  scripts/checkDependencies.js
  scripts/updateReadme.js
  templates/.gitignore.template
  test/checkDependencies.test.js
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: chore
