Repository milieuinfo/webcomponent-vl-ui-util, pull requests merged in 2020-04, with the labels that each got.

#139 Update dependency jsdom to v16.2.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#103 Update dependency sass to v1.26.3
  package-lock.json
  package.json
Labels: dependencies

#131 Update dependency yaml to v1.8.3
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#140 Update dependency chromedriver to v80.0.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#101 Update dependency prismjs to v1.20.0
  package-lock.json
  package.json
Labels: dependencies

#130 Update dependency selenium-webdriver to v4.0.0-alpha.7
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#132 Update dependency yargs to v15.3.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#143 Update dependency np to v6.2.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#144 Verwijder alle performance acties
  bamboo/templates/template.yml
  package.json
Labels: chore

#145 Scheduled runs uitschakelen
  bamboo/templates/template.yml
Labels: chore

#146 Update dependency yaml to v1.9.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#147 Update dependency yaml to v1.9.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#150 Update dependency yaml to v1.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#154 Update dependency np to v6.2.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#152 Oplossing voor src build problemen met relative src imports zonder from statement
  build.js
  package-lock.json
  test/build.test.js
  test/multiple/example/src/vl-example-other.js
  test/multiple/example/src/vl-example.js
  test/multiple/expected/vl-example-all.src.js
  test/multiple/expected/vl-example-other.js
  test/multiple/expected/vl-example-other.min.js
  test/multiple/expected/vl-example-other.src.js
  test/multiple/expected/vl-example.js
  test/multiple/expected/vl-example.min.js
  test/multiple/expected/vl-example.src.js
  test/single/example/src/vl-example.js
  test/single/expected/vl-example.js
  test/single/expected/vl-example.min.js
  test/single/expected/vl-example.src.js
Labels: bug

#155 Update dependency replace to v1.2.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#156 Update dependency sass to v1.26.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#157 Update dependency http-server to v0.12.3
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#158 Update dependency np to v6.2.3
  package.json
Labels: chore, dependencies, renovate
