Repository milieuinfo/webcomponent-vl-ui-util, pull requests merged in 2020-02, with the labels that each got.

#95 Stijl import vervangen door inhoud probleem met absolute paden
  exploder.js
Labels: bug

#96 Stijl vervangen ondersteuning toegevoegd voor enkele en dubbele quotes
  exploder.js
Labels: chore

#104 Update dependency chromedriver to v80
  package-lock.json
  package.json
Labels: dependencies

#100 Update dependency http-server to v0.12.1
  package-lock.json
  package.json
Labels: dependencies

#99 Update dependency copyfiles to v2.2.0
  package-lock.json
  package.json
Labels: dependencies

#102 Update dependency replace to v1.1.5
  package-lock.json
  package.json
Labels: dependencies

#106 Build script centraliseren
  build.js
  exploder.js
  package.json
  test/single/example/src/vl-example.src.js
  test/single/example/style.css
  test/single/example/vl-example.js
  test/single/example/vl-example.min.js
  test/single/example/vl-example.src.js
  test/single/expected/vl-example.js
  test/single/expected/vl-example.min.js
  test/single/expected/vl-example.src.js
Labels: chore

#105 Voeg cron schedule toe voor nachtelijke builds
  .mocharc.js
  bamboo/templates/template.yml
  bamboo/utils/util.js
  package-lock.json
Labels: chore

#109 Build script testen
  .mocharc.js
  build.js
  package-lock.json
  package.json
  test/build.test.js
  test/multiple/example/src/vl-example-other.js
  test/multiple/example/src/vl-example.js
  test/multiple/expected/vl-example-other.js
  test/multiple/expected/vl-example-other.src.js
  test/multiple/expected/vl-example.js
  test/multiple/expected/vl-example.src.js
Labels: chore

#110 Build script cleanup en commit problemen opgelost
  build.js
Labels: bug

#115 Commit package-lock changes bij release
  CODEOWNERS
  build.js
Labels: chore

#117 Git status log om te kunnen zien waarom een release fout loopt
  build.js
Labels: chore
