Repository milieuinfo/webcomponent-vl-ui-util, pull requests merged in 2020-01, with the labels that each got.

#70 #69 meta tag mobile browsers demo pagina
  demo.js
  package-lock.json
Labels: enhancement

#71 Generieke test en demo scripts toegevoegd
  package.json
Labels: chore

#79 Upgrade uglifyjs om disceprantie met @govflanders/vl-ui-util te fixen
  package-lock.json
  package.json
Labels: chore

#80 Update package-lock
  package-lock.json
Labels: chore

#81 Ruil uglify in voor minify
  package-lock.json
  package.json
Labels: chore

#82 Update package-lock
  package-lock.json
Labels: chore

#83 Voeg check op OS toe zodat sed correct werkt op Linux
  scripts/updateReadme.sh
Labels: bugfix

#84 UIG-266: Automatisch CSS minify uitvoeren
  package.json
Labels: enhancement

#85 Zet max-session en max-instance in docker op 3 en pas de bamboo spec aan zodat er drie containers per firefox en chrome worden opgestart
  bamboo/templates/template.yml
  package-lock.json
  test/docker-compose.yml
Labels: bugfix

#86 Verwijder aanmaken van meerdere instanties
  bamboo/templates/template.yml
Labels: bugfix

#87 Verwijder de port mapping in de compose zodat er meerdere instanties kunnen draaien
  bamboo/templates/template.yml
  test/docker-compose.yml
Labels: bugfix

#93 #92: Introductie docker-compose-release.yml
  bamboo-specs/bamboo.yml
  bamboo/templates/template.yml
  docker-compose-release.yml
  package.json
Labels: bug
