Repository milieuinfo/webcomponent-vl-ui-util, pull requests merged in 2020-03, with the labels that each got.

#122 Kenzo als standaard assignee van nieuwe issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
Labels: chore

#120 Build script moet met double en single quotes overweg kunnen
  build.js
  package-lock.json
  test/single/example/lib/external-library-2.js
  test/single/example/src/non-vl-2.js
  test/single/example/src/non-vl.js
  test/single/example/src/vl-example.js
  test/single/expected/non-vl-2.js
  test/single/expected/non-vl.js
  test/single/expected/vl-example.js
  test/single/expected/vl-example.min.js
  test/single/expected/vl-example.src.js
Labels: bug

#123 Update mocha dependency
  package-lock.json
  package.json
Labels: chore

#124 Performantie-testen abstractie naar vl-ui-util
  bamboo/templates/template.yml
  docker-compose-performance-chrome.yml
  docker-compose-performance-firefox.yml
  package.json
  performance/README.md
  performance/config/budget.json
  performance/config/config-chrome.json
  performance/config/config-firefox.json
  performance/generate.js
  performance/scripts/preScript.js
Labels: chore

#125 Update package-lock
  package-lock.json
Labels: bugfix

#126 File pattern voor copyfiles kopieerde niet beide performance.yml files
  package.json
Labels: bugfix

#127 Verhoog budget om testen te laten slagen Verander hostname van demo container om sitespeed-bug te counteren
  docker-compose-performance-chrome.yml
  performance/config/budget.json
Labels: bugfix

#129 Artifacts hoort thuis onder build task in bamboo-spec
  bamboo/templates/template.yml
Labels: chore

#138 Abstractie Mocha configuratie naar vl-ui-util
  package.json
Labels: chore

#134 Update dependency np to v6
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
