Repository milieuinfo/webcomponent-vl-ui-util, pull requests merged in 2020-06, with the labels that each got.

#175 Exclude dist folder bij het linten
  .eslintrc.json
Labels: chore

#178 Update dependency terser to v4.7.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#179 Update vl-ui-demo dependency
  package-lock.json
  package.json
Labels: chore

#180 Update vl-ui-demo dependency
  package-lock.json
  package.json
Labels: chore

#182 Introductie nieuwe CDN icon font url
  package.json
Labels: enhancement

#185 Kopieer de working files via rsync ipv cp zodat we node_modules kunnen excluden. Het kopieren van node_modules vertraagt het build process enorm
  test/docker-compose.yml
Labels: chore

#186 Update dependency terser to v4.8.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#187 Overschakelen op ubuntu-node:14 base image
  test/docker-compose.yml
Labels: chore

#189 Duplicatie scripts wegwerken
  .mocharc.js
  bamboo/templates/template.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore

#191 Voeg yargs toe als dependency
  package-lock.json
  package.json
Labels: chore

#192 Fix typo in NPM run scripts
  package-lock.json
  package.json
Labels: bugfix
