Repository milieuinfo/webcomponent-vl-ui-util, pull requests merged in 2021-06, with the labels that each got.

#277 Prettier config file toegevoegd
  .prettierrc.json
  package.json
Labels: feature

#274 Update dependency chromedriver to v91
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#278 Lint rules uitgebreid met prettier
  .eslintrc.json
  .prettierrc.json
  package-lock.json
  package.json
Labels: chore

#279 Update dependency selenium-standalone to v6.24.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#281 Dependency eslint-config-prettier verplaatst van dev naar dependencies
  package-lock.json
  package.json
Labels: chore
